version: '3.1'
services:
  db:
        image: postgres:10.6
        # image: mysql
        volumes:
          # - ~/usr/local/mysql:/var/lib/mysql
          - ~/usr/local/var/postgres:/var/lib/postgresql/data
        # environment:
        #     MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
